//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VilkaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public int ID { get; set; }
        public int OutcomeTypeID { get; set; }
        public Nullable<int> Line { get; set; }
        public string Odds { get; set; }
        public int BetOfferID { get; set; }
    
        public virtual OutcomeType OutcomeType { get; set; }
        public virtual BetOffer BetOffer { get; set; }
    }
}
