//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vilka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compare_Events
    {
        public int ID { get; set; }
        public int SportID { get; set; }
        public string League { get; set; }
        public string Region { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> PrematchEnd { get; set; }
        public int SiteID { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
