//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vilka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueDictionaryElement
    {
        public string Name { get; set; }
        public Nullable<int> LeagueID { get; set; }
        public int SportID { get; set; }
    
        public virtual League League { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
