//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vilka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public League()
        {
            this.LeagueDictionaryElements = new HashSet<LeagueDictionaryElement>();
            this.LeagueDictionaryOptimizationDatas = new HashSet<LeagueDictionaryOptimizationData>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int RegionID { get; set; }
        public int SportID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeagueDictionaryElement> LeagueDictionaryElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeagueDictionaryOptimizationData> LeagueDictionaryOptimizationDatas { get; set; }
        public virtual Region Region { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
